Adjusted cleanup messaging and pvc test

diff --git a/.github/workflows/cleanup.yml b/.github/workflows/cleanup.yml
--- a/.github/workflows/cleanup.yml
+++ b/.github/workflows/cleanup.yml
@@ -109,21 +109,28 @@ jobs:
             echo "Uninstalled helm ${{ inputs.REDIS_DEPLOYMENT_NAME }}"
           fi
 
-      # For a graceful termination, set the replica count of the Pods in the mariadb-galera StatefulSet to 0:
-      # oc scale sts ${{ inputs.DB_DEPLOYMENT_NAME }} --replicas=0
       - name: 🧹️ Cleanup ${{ inputs.DB_DEPLOYMENT_NAME }}
         run: |
+          configmap_name="${{ inputs.DB_DEPLOYMENT_NAME }}-config"
           if [[ `oc describe sts ${{ inputs.DB_DEPLOYMENT_NAME }} 2>&1` =~ "NotFound" ]]; then
             echo "${{ inputs.DB_DEPLOYMENT_NAME }} NOT FOUND: Skipping..."
           else
             echo "${{ inputs.DB_DEPLOYMENT_NAME }} FOUND: Cleaning..."
             oc scale sts ${{ inputs.DB_DEPLOYMENT_NAME }} --replicas=0
             oc delete sts ${{ inputs.DB_DEPLOYMENT_NAME }}
-            for i in 0 1 2; do kubectl delete pvc datadir-${{ inputs.DB_DEPLOYMENT_NAME }}-$i; done
+            for i in 0 1 2; do
+              if ! [[ `oc describe pvc datadir-${{ inputs.DB_DEPLOYMENT_NAME }}-$i 2>&1` =~ "NotFound" ]]; then
+                kubectl delete pvc datadir-${{ inputs.DB_DEPLOYMENT_NAME }}-$i;
+                echo "DELETED pvc datadir-${{ inputs.DB_DEPLOYMENT_NAME }}-$i"
+              else
+                echo "pvc datadir-${{ inputs.DB_DEPLOYMENT_NAME }}-$i NOT FOUND: Skipping..."
+              fi
+            done
             echo "DELETED sts ${{ inputs.DB_DEPLOYMENT_NAME }}"
           fi
-          if [[ `oc describe configmap ${{ inputs.DB_DEPLOYMENT_NAME }}-config 2>&1` =~ "NotFound" ]]; then
-            oc delete configmap ${{ inputs.DB_DEPLOYMENT_NAME }}-config
+          if [[ `oc describe configmap $configmap_name 2>&1` =~ "NotFound" ]]; then
+            oc delete configmap $configmap_name
+            echo "DELETED configmap $configmap_name"
           fi
           if [[ `oc describe service ${{ inputs.DB_DEPLOYMENT_NAME }} 2>&1` =~ "NotFound" ]]; then
             oc delete service ${{ inputs.DB_DEPLOYMENT_NAME }}
