Consolidate deployment into single process

diff --git a/.github/workflows/deploy-branch.yml b/.github/workflows/deploy-branch.yml
--- a/.github/workflows/deploy-branch.yml
+++ b/.github/workflows/deploy-branch.yml
@@ -28,61 +28,6 @@ jobs:
           echo OC CLI Version: $(oc version)
           echo Git Branch name: ${{ github.ref_name }}
 
-  #Build the app
-
-  build:
-    name: Build APP
-    runs-on: ubuntu-latest
-    if: github.ref_name == 'dev' || github.ref_name  == 'test' || github.ref_name  == 'prod'
-    env:
-      BUILD_ID: ${{ github.event.number }}
-      BUILD_NAMESPACE: e66ac2-tools
-      DEPLOY_NAMESPACE: e66ac2-${{ github.ref_name }}
-      BRANCH: ${{ github.ref_name }}
-      BUILD_TAG: ${{ github.ref_name }}
-      WEB_APP_NAME: web
-      BASE_WEB_IMAGE_NAME: nginx
-      BASE_WEB_IMAGE_TAG: latest
-      BASE_WEB_IMAGE_REPO: ""
-    steps:
-      # Checkout the PR branch
-      - name: Print env
-        run: |
-          echo BUILD ID: $BUILD_ID
-          echo BUILD NAMESPACE: $BUILD_NAMESPACE
-          echo BRANCH: $BRANCH
-      - name: Checkout Target Branch
-        uses: actions/checkout@v1
-      # Log in to OpenShift.
-      # Note: The secrets needed to log in are NOT available if the PR comes from a FORK.
-      # PR's must originate from a branch off the original repo or else all openshift `oc` commands will fail.
-      - name: Log in to OpenShift
-        run: |
-          oc login --token=${{ secrets.SA_TOKEN }} --server=https://api.silver.devops.gov.bc.ca:6443
-
-      # Build web deployment
-      - name: Build ${WEB_APP_NAME}
-        working-directory: "./openshift"
-        run: |
-          test -n "${BRANCH}"
-          test -n "${BUILD_NAMESPACE}"
-          echo "BUILIDING ${WEB_APP_NAME} confifMap: ${WEB_APP_NAME}-config"
-          oc create configmap ${WEB_APP_NAME}-config \
-            --from-file=nginx.conf=../builds/web/nginx.conf \
-            || echo "Secrets already exists in $DEPLOY_NAMESPACE"; \
-          echo "BUILIDING ${WEB_APP_NAME} in: ${DEPLOY_NAMESPACE}"
-          oc -n ${BUILD_NAMESPACE} process -f docker-build.yml \
-            -p TAG=${BUILD_TAG} \
-            -p SOURCE_REPOSITORY_REF=${BRANCH} \
-            -p BASE_IMAGE_NAME="${BASE_WEB_IMAGE_NAME}" \
-            -p BASE_IMAGE_TAG="${BASE_WEB_IMAGE_TAG}" \
-            -p BASE_IMAGE_REPO="${BASE_WEB_IMAGE_REPO}" \
-            -p SOURCE_CONTEXT_DIR=. \
-            -p NAME=${WEB_APP_NAME} | oc -n ${BUILD_NAMESPACE} apply -f - \
-            || echo "${WEB_APP_NAME} already exists in $BUILD_NAMESPACE";
-          oc -n ${BUILD_NAMESPACE} start-build bc/${WEB_APP_NAME} --no-cache --wait \
-            || echo "bc/${WEB_APP_NAME} already exists in $BUILD_NAMESPACE";
-
   # Deploy App
   deploy:
     name: Deploy
@@ -90,7 +35,7 @@ jobs:
     env:
       BUILD_ID: ${{ github.event.number }}
       CRON_PASSWORD: ${{ secrets.CRON_PASSWORD }}
-      NAMESPACE: e66ac2-${{ github.ref_name }}
+      DEPLOY_NAMESPACE: e66ac2-${{ github.ref_name }}
       BUILD_NAMESPACE: e66ac2-tools
       BRANCH: ${{ github.ref_name }}
       APP: moodle
@@ -139,14 +84,15 @@ jobs:
           oc create -f mariadb-sts-replication.yaml -n ${DEPLOY_NAMESPACE} \
           || echo "MariaDB already exists in $DEPLOY_NAMESPACE";
 
+      # Deploy Web (Nginx)
       - name: Deploy Web Service
         run: |
           test -n "${BUILD_NAMESPACE}"
           test -n "${DEPLOY_NAMESPACE}"
           test -n "${BRANCH}"
-          echo "Current namespace is ${NAMESPACE}"
+          echo "Current namespace is ${DEPLOY_NAMESPACE}"
           oc -n ${BUILD_NAMESPACE} process -f openshift/web.json \
-                -p APP_NAME=web \
+                -p APP_NAME=${WEB_APP_NAME} \
                 -p IMAGE_STREAM="nginx:latest" \
                 -p SITE_URL=${APP_HOST} \
                 -p MEMORY_LIMIT=512Mi \
@@ -157,33 +103,34 @@ jobs:
                 -p VOLUME_SIZE=10Gi \
                 -p MOODLE_DATA_PATH="/app/moodledata" \
                 -p MOODLE_DATA_MOUNT_PATH="/app" \
-                || echo "Web already exists in $BUILD_NAMESPACE";
+                || echo "${WEB_APP_NAME} already exists in $BUILD_NAMESPACE";
           oc -n ${DEPLOY_NAMESPACE} apply -f - \
           oc rollout latest dc/moodle -n ${BUILD_NAMESPACE} \
-            || echo "Web rollout cannot be completed in $BUILD_NAMESPACE";
+            || echo "${WEB_APP_NAME} rollout cannot be completed in $BUILD_NAMESPACE";
           # Check deployment rollout status every 10 seconds (max 10 minutes) until complete.
           ATTEMPTS=0
-          ROLLOUT_STATUS_CMD="oc rollout status dc/web -n ${DEPLOY_NAMESPACE}"
+          ROLLOUT_STATUS_CMD="oc rollout status dc/${WEB_APP_NAME} -n ${DEPLOY_NAMESPACE}"
           until $ROLLOUT_STATUS_CMD || [ $ATTEMPTS -eq 60 ]; do
             $ROLLOUT_STATUS_CMD
             ATTEMPTS=$((attempts + 1))
             sleep 10
           done
 
+      # Deploy PHP-FPM (Moodle)
       - name: Deploy PHP-FPM-Moodle
         run: |
-          test -n "${NAMESPACE}"
+          test -n "${DEPLOY_NAMESPACE}"
           test -n "${BUILD_NAMESPACE}"
           test -n "${BRANCH}"
-          echo "Current namespace is ${NAMESPACE}"
-          oc -n ${NAMESPACE} process -f openshift/php.json \
+          echo "Current namespace is ${DEPLOY_NAMESPACE}"
+          oc -n ${DEPLOY_NAMESPACE} process -f openshift/php.json \
                 -p APP_NAME=${PHP_APP_NAME} \
                 -p SITE_URL=${APP_HOST} \
                 -p MEMORY_LIMIT=1Gi \
                 -p MEMORY_REQUEST=128Mi \
                 -p CPU_LIMIT=1 \
                 -p CPU_REQUEST=0.2 \
-                -p PROJECT_NAMESPACE=${NAMESPACE} \
+                -p PROJECT_NAMESPACE=${DEPLOY_NAMESPACE} \
                 -p VOLUME_SIZE=10Gi \
                 -p HTTP_PORT=8080 \
                 -p DB_PORT=3306 \
@@ -193,13 +140,13 @@ jobs:
                 -p BUILD_NAMESPACE="${BUILD_NAMESPACE}" \
                 -p IMAGE_STREAM_TAG="moodle:${BRANCH}" \
                 || echo "PHP already exists in $BUILD_NAMESPACE";
-          oc -n ${NAMESPACE} apply -f - \
-            || echo "PHP template cannot be applied in $BUILD_NAMESPACE";
-          oc rollout latest dc/php -n ${NAMESPACE} \
-            || echo "PHP rollout failed in $BUILD_NAMESPACE";
+          oc -n ${DEPLOY_NAMESPACE} apply -f - \
+            || echo "${PHP_APP_NAME} template cannot be applied in $BUILD_NAMESPACE";
+          oc rollout latest dc/${PHP_APP_NAME} -n ${DEPLOY_NAMESPACE} \
+            || echo "${PHP_APP_NAME} rollout failed in $DEPLOY_NAMESPACE";
           # Check deployment rollout status every 10 seconds (max 10 minutes) until complete.
           ATTEMPTS=0
-          ROLLOUT_STATUS_CMD="oc rollout status dc/php -n ${NAMESPACE}"
+          ROLLOUT_STATUS_CMD="oc rollout status dc/${PHP_APP_NAME} -n ${DEPLOY_NAMESPACE}"
           until $ROLLOUT_STATUS_CMD || [ $ATTEMPTS -eq 60 ]; do
             $ROLLOUT_STATUS_CMD
             ATTEMPTS=$((attempts + 1))
